In [3]:
import numpy as np
lists = [1,2,3,4]
lists = lists.reverse()
print(lists)

None


In [28]:
lists = [1,2,3,4]
lists.reverse()
print(lists)
print(lists[5-4])

[4, 3, 2, 1]
3


In [10]:
import numpy as np
lists = [40,26,27,100,67,57,60]
lists = np.array(lists)
print(lists)
mean = lists.mean()
ranges = lists - mean
listes = np.arange(4)
print(listes)
#std_dev = np.std(lists)
#print(std_dev)

[ 40  26  27 100  67  57  60]
[0 1 2 3]


In [11]:
import numpy as np
lists = [1,2,3,4]
lists = np.array(lists)
np.arange(4)
print(lists)

[1 2 3 4]


In [36]:
import numpy as np
lists = [1,2,3,4]
lists = np.array(lists)
print(np.linspace(1,4,5))
print(lists)

[1.   1.75 2.5  3.25 4.  ]
[1 2 3 4]


In [19]:
x=[0 0.025 0.05 0.075 0.1 0.125 0.15 0.175 0.2 0.225 0.25 0.275 0.3 0.325 0.35 0.375 0.4 0.425 0.45 0.475 0.5 0.525 0.55 0.575 0.6 0.625 0.65 0.675 0.7 0.725 0.75 0.775 0.8 0.825 0.85 0.875 0.9 0.925 0.95 0.975 1 ]
y=[1.422 1.427 1.431 1.396 1.396 1.377 1.377 1.358 1.357 1.338 1.338 1.319 1.318 1.301 1.301 1.288 1.287 1.278 1.278 1.274 1.274 1.275 1.276 1.282 1.282 1.294 1.294 1.309 1.310 1.328 1.328 1.348 1.348 1.367 1.367 1.386 1.386 1.413 1.413 1.039 1.025]
len(x)

SyntaxError: invalid syntax (<ipython-input-19-b120bb82e8bc>, line 1)