In [3]:
import numpy as np
lists = [1,2,3,4]
lists = lists.reverse()
print(lists)

None


In [28]:
lists = [1,2,3,4]
lists.reverse()
print(lists)
print(lists[5-4])

[4, 3, 2, 1]
3


In [10]:
import numpy as np
lists = [40,26,27,100,67,57,60]
lists = np.array(lists)
print(lists)
mean = lists.mean()
ranges = lists - mean
listes = np.arange(4)
print(listes)
#std_dev = np.std(lists)
#print(std_dev)

[ 40  26  27 100  67  57  60]
[0 1 2 3]


In [11]:
import numpy as np
lists = [1,2,3,4]
lists = np.array(lists)
np.arange(4)
print(lists)

[1 2 3 4]


In [36]:
import numpy as np
lists = [1,2,3,4]
lists = np.array(lists)
print(np.linspace(1,4,5))
print(lists)

[1.   1.75 2.5  3.25 4.  ]
[1 2 3 4]
